name: Azure Connection Test

on:
  push:
    branches:
      - main

jobs:
  connect-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger Azure Test Connection Workflow
      uses: actions/workflow-dispatch@v2
      with:
        workflow: connexion-azure-test.yaml  # Nom du fichier du workflow à déclencher

    - name: Configure kubectl
      run: |
        az aks get-credentials --name k8-aks-cluster --resource-group rg-kubernetes-cluster

    - name: Test AKS Connectivity
      run: |
        kubectl get nodes
